import Head from 'next/head'
import { Portfolio } from '../components/Portfolio';
import { Post } from '../components/Post';
import { getPostAndPortfolios } from '../lib/data';

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.portfolios.map((portfolio,index) => (
          <Portfolio key={index} portfolio={portfolio}/>
        ))}

        <div className="mt-20">
            {data?.posts.map((post,index) => (
              <Post key={index} post={post}/>
            ))}
        </div>
        
      </main>
    </div>
  )
}



export const getServerSideProps = async (ctx) => {

  const data = await getPostAndPortfolios()

  return {
    props: {
      data
    }
  }
}