import Head from 'next/head'
import { Portfolio } from '../components/Portfolio';
import { Post } from '../components/Post';
import { getPostAndPortfolios } from '../lib/data';

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Portfolios.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-[1200px] mx-auto'>
        <div className="mt-10 Blogs text-5xl font-semibold py-4">Portfolios.</div>
        <div className="columns-3">
          {data?.portfolios.map((portfolio,index) => (
          <Portfolio key={index} portfolio={portfolio}/>
        ))}
        </div>
        
        <div className="my-20">
          <hr />
          <div className="mt-4 Blogs text-5xl font-semibold py-4">Blogs.</div>
          <div className=" columns-3">
            {data?.posts.map((post,index) => (
              <Post key={index} post={post}/>
            ))}
          </div>
        </div>
        
        
      </main>
    </div>
  )
}



export const getServerSideProps = async (ctx) => {

  const data = await getPostAndPortfolios()

  return {
    props: {
      data
    }
  }
}